# prettier-ignore
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.backendsecretname}}
  namespace: {{.Values.backendnamespace}}
type: Opaque
data:
  .env: REFUQUJBU0VfVVJMPSJtb25nb2RiOi8vZGIuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNy9sZWFybnNwaGVyZV9kYiIKUE9SVD0zMDAwCkpXVF9TRUNSRVRfVVNFUj0ic2hqMzIyZzd1NmZ2eTcydnl1Mmc4MSIKSldUX1NFQ1JFVF9BRE1JTj0iaTk5a2liODJ1Z2J3ODI3ODJpZ3diMjgi
