name: Deploy Nginx

on:
  push:
    branches:
      - master
    paths:
      - ops/nginx/nginx.conf

jobs:
  deploy-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy nginx config & SSL
        env:
          DOMAIN: learnsphere.deepak.cfd
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.60.168.88 << 'EOF'
            cd LearnSphere
            sudo cp ./ops/nginx/nginx.conf /etc/nginx/nginx.conf
            sudo nginx -t
            sudo systemctl restart nginx
            sudo apt-get update -y
            sudo apt-get install -y certbot python3-certbot-nginx
            sudo certbot --nginx -d $DOMAIN --non-interactive --agree-tos --register-unsafely-without-email
          EOF
