name: Deploy Nginx for Vercel frontend

on:
  workflow_run:
    workflows: ["Deploy to EC2 on Every push to master branch"]
    types:
      - completed

jobs:
  deploy-nginx-vercel:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect if nginx-vercel.conf changed
        id: check_nginx
        run: |
          git fetch origin master
          if git diff --name-only origin/master~1 origin/master | grep -q '^ops/nginx/nginx-vercel.conf'; then
            echo "NGINX_CHANGED=true" >> $GITHUB_ENV
          fi

      - name: Skip if nginx-vercel.conf not changed
        if: env.NGINX_CHANGED != 'true'
        run: |
          echo "nginx-vercel.conf not changed. Skipping deployment."
          exit 78  # Neutral exit, workflow marked as skipped

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy nginx config & SSL
        if: env.NGINX_CHANGED == 'true'
        env:
          DOMAIN: learnsphere-vercel.api.deepak.cfd
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.60.168.88 << EOF
            cd /home/ubuntu/LearnSphere
            sudo cp ./ops/nginx/nginx-vercel.conf /etc/nginx/nginx.conf
            sudo nginx -t && sudo systemctl reload nginx

            if ! command -v certbot >/dev/null; then
              sudo apt-get update -y
              sudo apt-get install -y certbot python3-certbot-nginx
            fi

            sudo certbot --nginx -d $DOMAIN --non-interactive --agree-tos --register-unsafely-without-email
          EOF
